const options = [
    { value: 'skopje', label: 'Skopje' },
    { value: 'bitola', label: 'Bitola' },
    { value: 'radovis', label: 'Radovis' },
    { value: 'Berovo', label: 'Berovo' },
    { value: 'Valandovo', label: 'Valandovo' },
    { value: 'Veles', label: 'Veles' },
    { value: 'vinica', label: 'Vinica' },
    { value: 'Gevgelija', label: 'Gevgelija' },
    { value: 'Gostivar', label: 'Gostivar' },
    { value: 'debar', label: 'Debar' },
    { value: 'Delcevo', label: 'Delcevo' },
    { value: 'demir hisar', label: 'Demir Hisar' },
    { value: 'Kavadarci', label: 'Kavadarci' },
    { value: 'Kicevo', label: 'Kicevo' },
    { value: 'Kocani', label: 'Kocani' },
    { value: 'Kratovo', label: 'Kratovo' },
    { value: 'kriva palanka', label: 'Kriva Palanka' },
    { value: 'krusevo', label: 'Krusevo' },
    { value: 'Kumanovo', label: 'Kumanovo' },
    { value: 'makedonski brod', label: 'Makedonski Brod' },
    { value: 'Negotino', label: 'Negotino' },
    { value: 'Ohrid', label: 'Ohrid' },
    { value: 'prilep', label: 'Prilep' },
    { value: 'Probistip', label: 'Probistip' },
    { value: 'Resen', label: 'Resen' },
    { value: 'Sveti Nikole', label: 'Sveti Nikole' },
    { value: 'Struga', label: 'Struga' },
    { value: 'Strumica', label: 'Strumica' },
    { value: 'Tetovo', label: 'Tetovo' },
    { value: 'stip', label: 'Stip' },
];

export default options;